"""
Health Status Endpoint

Flask route that aggregates and returns health status of all components.
Generated by code-agent, integrated manually.
"""

from flask import Flask, jsonify
from health_aggregator import HealthAggregator

app = Flask(__name__)

@app.route("/status", methods=["GET"])
def get_status():
    """
    Returns the health status of the coordinator, code-agent, and fenrir-executor.
    """
    health_aggregator = HealthAggregator()
    coordinator_health = health_aggregator.get_coordinator_health()
    code_agent_health = health_aggregator.get_code_agent_health()
    fenrir_executor_health = health_aggregator.get_fenrir_executor_health()

    status = {
        "coordinator": coordinator_health,
        "code-agent": code_agent_health,
        "fenrir-executor": fenrir_executor_health,
    }

    return jsonify(status)

if __name__ == "__main__":
    app.run()
